name: mkdocs-test
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - mkdocs-material
    - mkdocs-glightbox
    - mkdocs-timetoread-plugin
    - mkdocs-drawio-file
    - mkdocs-encryptcontent-plugin
    - mkdocs-git-revision-date-localized-plugin
    - neoteroi-mkdocs
    - mkdocs-include-dir-to-nav
    - mkdocs-rss-plugin
